### ISSUE TITLE
Class names in QUICK should be user-friendly

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/qi-core#3]
The Class names as displayed in QUICK appear to be the profile names (e.g. qicore-adverseevent), rather than the user-friendly AdverseEvent. The intent of the QUICK documentation is to provide the author's logical view of the content, so the user-friendly name should be used.

**Comment by c-schuler** [comment]
Yes, I am working on this. This is also causing broken links for substructures like http://build.fhir.org/ig/cqframework/qi-core/quick/pages/Condition.Evidence.html.
The "Condition" breadcrumb link ends in a 404.

**Comment by hstrasbe** [comment]
Looking at http://build.fhir.org/ig/cqframework/qi-core/quick/index.html, this issue appears to be resolved.  Is that correct?

**Comment by c-schuler** [comment]
Yes, thank you.
